apiVersion: v1
kind: ConfigMap
metadata:
  name: jr-app-config
  namespace: jr-namespace
  labels:
    app: milestone2
    tier: config
data:
  MONGO_HOST: "jr-database-service"
  MONGO_PORT: "27017"
  MONGO_DB: "milestone2"
  API_HOST: "jr-api-service"
  API_PORT: "8000"