apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jr-ingress
  namespace: jr-namespace
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - localhost
    secretName: jr-tls-secret
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jr-frontend-service
            port:
              number: 80