apiVersion: v1
kind: Secret
metadata:
  name: jr-db-secret
  namespace: jr-namespace
  labels:
    app: milestone2
    tier: config
type: Opaque
stringData:
  MONGO_INITDB_DATABASE: "milestone2"